# Generated by Django 4.0.3 on 2022-04-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_link', models.URLField(auto_created=True, default='', primary_key=True, serialize=False, unique=True, verbose_name='Ссылка на профиль')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='ФИО')),
                ('birthday', models.DateField(blank=True, default='11.11.1111', verbose_name='День рождения')),
                ('occupation', models.CharField(blank=True, max_length=20, verbose_name='Профессия')),
                ('sales_number', models.IntegerField(default=0, verbose_name='Кол-во продаж')),
                ('sales_value', models.IntegerField(default=0, verbose_name='Сумма продаж')),
                ('debt', models.IntegerField(default=0, verbose_name='Задолженность')),
                ('notes', models.TextField(blank=True, max_length=300, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MoneyFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_spendings', models.IntegerField(default=0, verbose_name='Расходы на продукцию')),
                ('order_making_spendings', models.IntegerField(default=0, verbose_name='Расходы на оформление заказов')),
                ('gasoline_spendings', models.IntegerField(default=0, verbose_name='Транспортные расходы')),
                ('other_spendings', models.IntegerField(default=0, verbose_name='Прочие расходы')),
                ('total_spendings', models.IntegerField(default=0, verbose_name='Общие расходы')),
                ('income', models.IntegerField(default=0, verbose_name='Доходы')),
                ('disc_profit', models.IntegerField(default=0, verbose_name='Прибыль (с вычетом спецпредложений)')),
                ('gen_profit', models.IntegerField(default=0, verbose_name='Прибыль (общая)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_link', models.URLField(auto_created=True, default='', primary_key=True, serialize=False, unique=True, verbose_name='Ссылка на страницу товара')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование ')),
                ('product_type', models.CharField(blank=True, max_length=30, verbose_name='Тип')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('exp_date', models.DateField(verbose_name='Срок годности')),
                ('sold', models.BooleanField(default=False, verbose_name='Куплено')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Покупатель', to='app.client')),
                ('product', models.ManyToManyField(to='app.product')),
            ],
        ),
    ]
